# Generated by Django 5.0.6 on 2024-05-29 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_no', models.CharField(max_length=10)),
                ('state_name', models.CharField(max_length=100)),
                ('state_code', models.CharField(max_length=10)),
            ],
        ),
    ]
