# Generated by Django 5.0.6 on 2024-05-29 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StateCode',
            fields=[
                ('state_id', models.AutoField(primary_key=True, serialize=False)),
                ('state_no', models.IntegerField(unique=True)),
                ('state_name', models.CharField(max_length=100)),
                ('state_code', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='State',
        ),
    ]
